Repository rpa-tomorrow/rpa-tomorrow, pull requests merged in 2020-11, with the labels that each got.

#90 Move demos/examples to examples directory #77
  examples/email_demo.py
  examples/email_name_demo.py
  examples/reminder_demo.py
  examples/schedule_demo.py
  requirements.txt
Labels: enhancement, feature

#96 95 pickle jar
  lib/automate/modules/schedule.py
  pickle_jar/.gitignore
Labels: enhancement, feature

#100 Fix pull request template
  .github/ISSUE_TEMPLATE/pull-request-.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: CI/CD

#99 Split module parsing and execution for dry-runs
  examples/email_demo.py
  examples/email_name_demo.py
  examples/reminder_demo.py
  examples/schedule_demo.py
  lib/automate/__init__.py
  lib/automate/modules/__init__.py
  lib/automate/modules/reminder.py
  lib/automate/modules/schedule.py
  lib/automate/modules/send.py
  lib/cli/config.py
  lib/nlp/nlp.py
  lib/settings.py
  tests/automate/modules/reminder/conftest.py
  tests/automate/modules/reminder/test_run.py
Labels: automation

#103 Fixed the scheduale time zone bug
  lib/automate/modules/schedule.py
  lib/automate/modules/tools/time_convert.py
  substorm-nlp.yml
Labels: automation, bug

#107 Make it easier to change models used
  config/nlp_models.yaml
  config/user.yaml
  examples/email_demo.py
  examples/email_name_demo.py
  examples/reminder_demo.py
  examples/schedule_demo.py
  lib/automate/__init__.py
  lib/automate/modules/__init__.py
  lib/automate/modules/reminder.py
  lib/automate/modules/schedule.py
  lib/automate/modules/send.py
  lib/cli/cli.py
  lib/cli/commands.py
  lib/cli/config.py
  lib/cli/helpprompt.txt
  lib/nlp/nlp.py
  lib/settings.py
Labels: automation, cli, feature

#113 Moved lib/automate/modules/tools/ to lib/utils
  lib/automate/modules/reminder.py
  lib/automate/modules/schedule.py
  lib/automate/modules/send.py
  lib/utils/tools/time_convert.py
Labels: enhancement

#108 Add variable debug option to CLI
  lib/cli/cli.py
Labels: cli, enhancement

#119 Fetch multiple contacts from Google Contacts
  lib/automate/google.py
  lib/automate/modules/schedule.py
  lib/automate/modules/send.py
  lib/utils/contacts.py
Labels: automation, discussion

#117 Download and install NLP models using cli
  config/language_releases.yaml
  config/nlp_models.yaml
  config/user.yaml
  lib/cli/commands.py
  lib/cli/config.py
  lib/cli/helpprompt.txt
  lib/nlp/model_installer.py
  lib/settings.py
Labels: cli, enhancement
