Repository rpa-tomorrow/rpa-tomorrow, pull requests merged in 2020-12, with the labels that each got.

#178 Prompt the user before executing task
  lib/automate/modules/reminder.py
  lib/automate/modules/remove_schedule.py
  lib/automate/modules/schedule.py
  lib/automate/modules/send.py
  lib/automate/modules/update_schedule.py
  lib/selector/selector.py
  lib/utils/contacts.py
  tests/selector/conftest.py
  tests/selector/use_cases/conftest.py
Labels: automation, enhancement

#203 Update automate/__init__
  lib/automate/__init__.py
Labels: automation, bug

#201 149 how to add new modules
  docs/automation_module.md
  docs/templates/automation_module_template.py
Labels: automation, documentation

#200 fixed GUI bug with renaming contacts
  src/main/python/contacts_view.py
Labels: bug, gui

#206 175 gui followup
  lib/automate/__init__.py
  src/main/python/design_view.py
  src/main/python/modal.py
  src/main/qss/base.qss
Labels: automation, gui

#208 Fixed the install command
  config/language_releases.yaml
  config/nlp_models.yaml
Labels: bug, cli

#210 Fix handling of answer on single contact followup
  lib/utils/contacts.py
Labels: automation, cli, enhancement

#212 Fix freebusy return value
  lib/automate/google.py
  lib/automate/modules/schedule.py
Labels: automation, bug

#209 GUI - Execute tasks
  lib/automate/modules/schedule.py
  src/main/python/design_view.py
  src/main/python/main.py
  src/main/python/play_view.py
  src/main/python/process_models.py
  src/main/python/run_view.py
  src/main/qss/base.qss
Labels: automation, gui

#213 177 gui info view
  src/main/images/97gushan.png
  src/main/images/Aleman778.jpg
  src/main/images/Blinningjr.png
  src/main/images/hugowangler.png
  src/main/images/markhakansson.jpg
  src/main/images/viktorfrom.jpg
  src/main/images/widforss.jpg
  src/main/python/design_view.py
  src/main/python/info_view.py
  src/main/python/main.py
  src/main/python/resources.py
  src/main/python/resources.qrc
  src/main/qss/base.qss
Labels: documentation, gui
