Repository rpa-tomorrow/rpa-tomorrow, pull requests merged in 2020-10, with the labels that each got.

#31 Add issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/pull-request-.md
Labels: documentation

#13 Create basic CI Pipeline
  .github/workflows/python-package-conda.yml
  lib/__init__.py
  lib/automate/__init__.py
  lib/automate/modules/send.py
  lib/cli/cli.py
  lib/cli/commands.py
  lib/nlp/nlp.py
  lib/settings.py
  tests/test_example.py
Labels: CI/CD

#42 Implement automation module for scheduling a meeting
  README.md
  email_demo.py
  lib/automate/__init__.py
  lib/automate/modules/schedule.py
  lib/nlp/nlp.py
  lib/settings.py
  requirements-dev.txt
  schedule_demo.py
Labels: enhancement

#48 Add pytest config
  .coveragerc
  README.md
  pytest.ini
  substorm-nlp.yml
  tests/test_active.py
  tests/test_example.py
Labels: CI/CD

#49 Add Reminder automation module
  lib/__init__.py
  lib/automate/__init__.py
  lib/automate/modules/reminder.py
  lib/cli/commands.py
  reminder_demo.py
  tests/automate/modules/reminder/conftest.py
  tests/automate/modules/reminder/test_notify.py
  tests/automate/modules/reminder/test_run.py
  tests/conftest.py
Labels: automation, enhancement

#52 Get email from contact book when a name is entered
  .github/workflows/python-package-conda.yml
  email_name_demo.py
  lib/__init__.py
  lib/automate/modules/reminder.py
  lib/automate/modules/send.py
  lib/nlp/nlp.py
  lib/settings.py
  tests/automate/modules/reminder/conftest.py
  tests/automate/modules/send/conftest.py
  tests/automate/modules/send/test_email.py
Labels: automation, enhancement

#55 Run follow-up questions on any invalid input
  lib/automate/modules/__init__.py
  lib/automate/modules/reminder.py
  lib/automate/modules/schedule.py
  lib/automate/modules/send.py
Labels: automation

#61 Simple model integration
  .github/workflows/python-package-conda.yml
  README.md
  email_demo.py
  lib/automate/modules/reminder.py
  lib/automate/modules/schedule.py
  lib/cli/commands.py
  lib/nlp/__nlp__py
  lib/nlp/nlp.py
  lib/nlp/time_convert.py
  schedule_demo.py
  substorm-nlp.yml
Labels: api, enhancement, nlp

#66 Google calendar
  .gitignore
  README.md
  lib/automate/modules/schedule.py
  lib/settings.py
  schedule_demo.py
Labels: automation, enhancement

#67 Config User
  config/contacts.yaml
  config/user.yaml
  email_demo.py
  email_name_demo.py
  lib/automate/__init__.py
  lib/automate/modules/schedule.py
  lib/automate/modules/send.py
  lib/cli/cli.py
  lib/cli/config.py
  lib/nlp/nlp.py
  lib/settings.py
  reminder_demo.py
  schedule_demo.py
  substorm-nlp.yml
  tests/automate/modules/send/conftest.py
Labels: automation, enhancement

#68 Check if users are busy when an event is created.
  lib/automate/modules/schedule.py
Labels: automation

#75 Refactor project to use smaller models
  config/user.yaml
  email_name_demo.py
  lib/automate/__init__.py
  lib/automate/modules/__init__.py
  lib/automate/modules/reminder.py
  lib/automate/modules/schedule.py
  lib/automate/modules/send.py
  lib/automate/modules/tools/time_convert.py
  lib/cli/cli.py
  lib/cli/commands.py
  lib/nlp/__nlp__py
  lib/nlp/nlp.py
  reminder_demo.py
  schedule_demo.py
  scripts/formatter.sh
  tests/automate/modules/reminder/conftest.py
Labels: enhancement
